name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  build:
    name: Сборка .NET
    uses: DaemonSharps/CI-CD/.github/workflows/build.yml@stable
      
  update_draft_release:
    name: Обновление черновика релиза
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release-drafter.outputs.tag_name }}
    steps:

      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_on_hub:
    name: Загрузка в Docker hub
    needs:
     - build
     - update_draft_release
    uses: DaemonSharps/CI-CD/.github/workflows/docker-deploy.yml@stable
    with:
      version_tags: |
        daemonsharps/garage-api:dev-${{ github.run_number }}.${{ github.run_id }}.${{ github.run_attempt }}
        daemonsharps/garage-api:dev-latest
        daemonsharps/garage-api:${{ needs.update_draft_release.outputs.release_tag }}
        daemonsharps/garage-api:latest
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_USER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_USER_AUTH_TOKEN }}

